### ISSUE TITLE
Kirby 4 compatibility

### ISSUE THREAD

**Issue by adamkiss** [jan-herman/kirby-colorextractor#1]
K4 reshuffled some classes around, and the `Field` now lives in the `Kirby\Content` namespace, not `Kirby\Cms`, so the after create/update file hook fails.

I switched back the version by Sylvain myself, but if you ever get around to updating one of your sites to K4, you might want to change the return class from the extract method.

**Comment by jan-herman** [comment]
Hi, thanks for the reminder. I've also switched back to Sylvain's plugin with K4. I've left this here just for the older projects and will probably deprecate it at some point. However, I pushed v2.0 with K4 support in case anyone needs it.

**Comment by adamkiss** [comment]
> I've also switched back to Sylvain's plugin with K4.

😂

**Comment by jan-herman** [comment]
This was always just a quick fork that (at the time) solved php 8 compatibility. Never intended for anyone else to actually use it. 

But it still might be useful to someone who prefers Color Thief (or any other library) to ColorExtractor. At least as an inspiration.
